// src/promptLibrary.js
export const promptLibrary = {
  hodl: [
    "A character heroically protecting a glowing coin from a raging storm of red downward-pointing arrows, standing firm.",
    "A tranquil character meditating on a mountaintop, levitating a single, glowing coin, unshaken by a chaotic storm of market charts.",
    "A determined character as a ship captain, holding a glowing crypto coin like a compass and steering a small boat through a giant hurricane.",
    "A character sitting on a treasure chest full of a single type of coin, refusing to open it, while ghosts whisper 'sell' in their ear.",
    "A character literally holding on for dear life to a wildly bucking mechanical bull shaped like a giant coin.",
    "A character frozen in a block of ice, still clutching a glowing coin.",
    "A weightlifter character struggling to hold a massive barbell, with glowing coins as weights.",
    "An old tree with deep roots, with a single, glowing coin embedded in its trunk, and a character hugging the tree.",
    "A character in a bunker, surrounded by canned food and a single glowing coin on a pedestal under a spotlight.",
    "A character refusing to let go of a kite shaped like a coin in a massive storm.",
  ],
  fud: [
    "A character being whispered to by shadowy, ghost-like figures, looking scared and about to sell their crypto.",
    "A character looking at a computer screen showing scary-looking news monsters trying to crawl out.",
    "A character trying to sleep, but their bed is surrounded by floating, scary newspaper headlines about crypto crashing.",
    "A character building a strong wall of bricks, but tiny cracks appear with fearful faces peeking through, representing doubt.",
    "A character walking through a thick fog, where the fog shapes into scary faces and question marks.",
    "A crowd of people pointing and laughing at a character holding a single coin.",
    "A character's reflection in a mirror is a scary, distorted version of themselves telling them to sell.",
    "Poisonous-looking mushrooms with skull patterns growing around a glowing coin, a character looks on in fear.",
    "A character being bombarded by tiny, angry-looking creatures with newspaper hats.",
    "A character's phone screen showing a crypto app, but the app is melting like a Dali clock.",
  ],
  "rug pull": [
    "A villain character literally pulling a giant rug from under a group of happy investors, who are falling as the villain runs away with bags of money.",
    "A character jumps into a beautiful swimming pool, but a second panel reveals the pool was just a painting on the desert ground.",
    "A character is about to bite into a delicious cake, but a cross-section reveals the cake is made of cardboard and paint.",
    "A shady character leading a group of investors up a staircase that suddenly disappears, leaving them to fall.",
    "A character pulling a string that unravels a beautiful sweater, revealing a stick figure underneath.",
    "A magician doing a disappearing act with an investor's money vault.",
    "A 'free money' stand that folds up into a suitcase and runs away when someone approaches.",
    "A piñata that, when broken, releases dust and cobwebs instead of candy.",
    "A beautiful bridge that collapses right after a character steps off it.",
    "A treasure map that leads to a drawing of a treasure chest on a rock.",
  ],
  whale: [
    "A giant, majestic blue whale wearing a top hat and monocle, swimming past tiny fish (small investors). The whale's movement is causing huge waves.",
    "A character playing chess, where the opponent is a giant, literal whale. The chess pieces are tiny, scared-looking investors.",
    "The giant shadow of a whale passes over a city made of crypto charts, causing the buildings to fluctuate wildly.",
    "A tiny character trying to fish in the ocean, but a massive whale surfaces right next to their tiny boat, looking amused.",
    "A giant whale cannonballing into a tiny swimming pool, splashing all the water and the small investors out.",
    "A character at a grocery store, but a giant whale is putting all the crypto coins in its shopping cart.",
    "A character on a seesaw, but a giant whale sits on the other end, launching the character into the sky.",
    "A tiny car stuck in traffic behind a giant whale that is taking up all the lanes of the highway.",
    "A character trying to build a sandcastle, but a giant whale's tail swipe destroys it.",
    "A giant whale sleeping on a huge pile of crypto coins like a dragon on its hoard.",
  ],
  "to the moon": [
    "A character strapped to a giant crypto coin rocket, blasting off towards a cartoonish, smiling moon, with confetti everywhere.",
    "A crypto coin reimagined as a giant hot air balloon, lifting a basket with a happy character into the sky.",
    "A character dressed as an astronaut planting a flag with a crypto logo on the moon's surface, looking triumphant.",
    "A character bouncing on a giant trampoline shaped like a crypto chart, launching themselves towards a smiling moon.",
    "A character literally climbing a staircase made of glowing green chart candles that leads into the starry night sky.",
    "A crypto coin with angel wings, ascending into the heavens past clouds.",
    "A group of characters having a party on the surface of the moon, with a crypto logo flag planted nearby.",
    "A character pulling the lever on a giant slot machine, and the result is three moon symbols.",
    "A character watering a tiny plant that grows into a giant beanstalk reaching the moon, with coin-shaped leaves.",
    "A character riding a crypto coin like a surfboard on a massive wave that is heading towards the moon.",
  ],
  "diamond hands": [
    "A close-up of a character's hands, which are literally made of sparkling, unbreakable diamonds, firmly holding a glowing crypto coin during a chaotic market storm.",
    "A weathered, ancient statue of a character with hands made of diamond, covered in moss, showing they have been holding a coin for ages.",
    "A character as a blacksmith, forging a pair of hands out of a giant, rough diamond at a glowing anvil.",
    "A character using their diamond hands to shield themselves from a barrage of falling red arrows.",
    "A character's hands are diamonds, and they are crushing a piece of coal into another diamond. The coal is labeled 'market crash'.",
    "A character with diamond hands is casually leaning against a wall while a volcano erupts with red charts in the background.",
    "A museum exhibit displaying a pair of fossilized diamond hands holding a single, ancient-looking coin.",
    "A character with diamond hands playing poker, going 'all-in' with a calm, unreadable expression.",
    "A close-up on a character's diamond hands, showing a reflection of a crashing market, but the hands are not shaking.",
    "A character with diamond hands is arm-wrestling a giant, scary bear, and winning.",
  ],
  "paper hands": [
    "A character with hands made of flimsy, tearing paper, trying to hold a crypto coin that is slipping through their fingers.",
    "A character trying to catch falling golden coins with hands made of paper, but the paper gets soaked and dissolves.",
    "A character carefully building a house of cards, but a small, comical sneeze from off-screen makes it collapse.",
    "A character's paper hands turning into paper airplanes and flying away, leaving the coins behind.",
    "A character with paper hands trying to block a tiny red arrow, but the arrow rips right through the hands.",
    "A character with paper hands is blown away by a small gust of wind labeled '0.1% dip'.",
    "A character is trying to high-five another character, but their paper hands just crumple.",
    "A character trying to hold water in their paper hands, but it leaks out immediately.",
    "A character whose hands are on fire, representing panic selling, because they are made of paper.",
    "A character holds up their paper hands, and you can see their scared face right through the paper.",
  ],
  "gas fees": [
    "A character trying to send a tiny crypto coin through a pipeline, but a huge, comically large gas pump meter is demanding a giant bag of money.",
    "A character on a digital highway with a massive toll booth. The toll price is ridiculously high. A tiny car, representing a transaction, is stuck.",
    "A character trying to mail a tiny letter, but the post office clerk is stamping it with a giant, heavy, expensive-looking stamp.",
    "A character trying to buy a single gumball from a machine, but the coin slot is for a giant bag of money.",
    "A character is at a restaurant. The bill for a tiny appetizer is a long, scrolling piece of paper labeled 'Gas Fee'.",
    "A character trying to jump over a very small puddle, but a giant troll is demanding a toll.",
    "A character trying to open a door, but the doorknob is a giant, complex safe dial.",
    "A character trying to pay for a cup of coffee, but the credit card machine has a giant exhaust pipe spewing out money.",
    "A tiny spark trying to ignite a fire, but it's being doused by a giant fire extinguisher.",
    "A character is giving a piggy bank to another, but a huge, muscular arm comes out of nowhere and takes most of the coins from inside.",
  ],
};
